import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1B2838',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#171A21',
    paddingVertical: 12,
    paddingHorizontal: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#2A475E',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerButton: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  headerButtonText: {
    color: '#66C0F4',
    fontSize: 14,
    fontWeight: '500',
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#171A21',
    borderBottomWidth: 1,
    borderBottomColor: '#2A475E',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  tabButton: {
    flex: 1,
    marginHorizontal: 6,
    borderRadius: 4,
    backgroundColor: '#2A3F5A',
    paddingVertical: 8,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#66C0F4',
  },
  tabButtonText: {
    color: '#8F98A0',
    fontSize: 13,
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: '#0B1A2B',
  },
  searchContainer: {
    flexDirection: 'row',
    backgroundColor: '#2A3F5A',
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1B2838',
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#316282',
    borderRadius: 3,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#FFFFFF',
    fontSize: 14,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginLeft: 10,
    justifyContent: 'space-between',
    width: 130,
  },
  actionButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#316282',
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 60,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  gamesList: {
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  loadingText: {
    color: '#8F98A0',
    marginTop: 12,
    fontSize: 16,
  },
  emptyContainer: {
    padding: 24,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#8F98A0',
    textAlign: 'center',
  },
  newsContainer: {
    flex: 1,
    backgroundColor: '#1B2838',
  },
  newsFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#171A21',
    borderBottomWidth: 1,
    borderBottomColor: '#2A475E',
  },
  newsFilterLabel: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  newsListContent: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: 32,
  },
  newsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
  },
  newsCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  newsGameName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1B2838',
  },
  newsMetaText: {
    fontSize: 12,
    color: '#4B5C6B',
  },
  newsFollowButton: {
    padding: 6,
  },
  newsTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#212121',
  },
  newsErrorContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#8B0000',
  },
  newsErrorText: {
    color: '#FFFFFF',
    textAlign: 'center',
  },
  loadingMoreContainer: {
    backgroundColor: 'rgba(35, 60, 95, 0.8)',
    padding: 10,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  loadingMoreText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#2A3F5A',
    borderRadius: 3,
    padding: 16,
    width: '80%',
    maxWidth: 300,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  sortOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 3,
    marginBottom: 8,
  },
  sortOptionText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  selectedSortOption: {
    backgroundColor: '#316282',
  },
});
