export const TUTORIAL_STEPS = [
  {
    id: 'home-intro',
    screen: 'Actu',
    targetTab: 'Fil',
    targetId: null,
    titleKey: 'tutorial.steps.homeIntro.title',
    descriptionKey: 'tutorial.steps.homeIntro.description',
  },
  {
    id: 'home-news-followed',
    screen: 'Actu',
    targetTab: 'JeuxSuivis',
    targetId: null,
    titleKey: 'tutorial.steps.homeNewsFollowed.title',
    descriptionKey: 'tutorial.steps.homeNewsFollowed.description',
  },
  {
    id: 'home-my-games',
    screen: 'SuivreUnJeu',
    targetTab: 'MesJeux',
    targetId: null,
    titleKey: 'tutorial.steps.homeMyGames.title',
    descriptionKey: 'tutorial.steps.homeMyGames.description',
  },
  {
    id: 'home-wishlist',
    screen: 'SuivreUnJeu',
    targetTab: 'Wishlist',
    targetId: null,
    titleKey: 'tutorial.steps.homeWishlist.title',
    descriptionKey: 'tutorial.steps.homeWishlist.description',
  },
  {
    id: 'home-search',
    screen: 'SuivreUnJeu',
    targetTab: 'Rechercher',
    targetId: null,
    titleKey: 'tutorial.steps.homeSearch.title',
    descriptionKey: 'tutorial.steps.homeSearch.description',
  },
  {
    id: 'home-settings',
    screen: 'MonCompte',
    targetTab: 'Settings',
    targetId: null,
    titleKey: 'tutorial.steps.homeSettings.title',
    descriptionKey: 'tutorial.steps.homeSettings.description',
  },
  {
    id: 'settings-notifications',
    screen: 'Settings',
    targetId: 'settings-notifications',
    titleKey: 'tutorial.steps.settingsNotifications.title',
    descriptionKey: 'tutorial.steps.settingsNotifications.description',
  },
  {
    id: 'settings-library',
    screen: 'Settings',
    targetId: 'settings-library',
    titleKey: 'tutorial.steps.settingsLibrary.title',
    descriptionKey: 'tutorial.steps.settingsLibrary.description',
  },
  {
    id: 'settings-wishlist',
    screen: 'Settings',
    targetId: 'settings-wishlist',
    titleKey: 'tutorial.steps.settingsWishlist.title',
    descriptionKey: 'tutorial.steps.settingsWishlist.description',
  },
  {
    id: 'settings-summary',
    screen: 'Settings',
    targetId: null,
    titleKey: 'tutorial.steps.settingsSummary.title',
    descriptionKey: 'tutorial.steps.settingsSummary.description',
    isSummary: true,
  },
];

export const SUMMARY_STEP_INDEX = TUTORIAL_STEPS.length - 1;
